@startuml c4-gtron-container
!include c4/C4_Container.puml
' !include c4/C4_Context.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/angular.puml
!include DEVICONS/dotnet.puml
!include DEVICONS2/dot_net.puml
!include DEVICONS2/dot_net_wordmark.puml
!include DEVICONS2/dotnetcore.puml
!include DEVICONS/msql_server.puml
!include FONTAWESOME/users.puml
!include FONTAWESOME/file_csv.puml

title Diagrama de Container do Sistema Growtron

LAYOUT_TOP_DOWN()
' LAYOUT_LEFT_RIGHT()
' LAYOUT_LANDSCAPE()
Person(pessoa, "Pessoa")

Boundary(sistemaGrowM5stack, "Sistema Growtron de Automação de Cultivo", "M5stack") {
    Container(centralCore2, "Central Core2", "MicroPython, UiFlow", "Exibe e controla os serviços do Grow", $sprite="img:icons/micropython-logo02.png")
    Container(dhtAtom, "DHT Atom Matrix", "C#, .NET nanoFramework", "Leitura dos dados do sensor DHT", $sprite="img:icons/nanoFramework3.png")
    Container(releAtom, "Fotoperiodo Atom Lite", "C#, .NET nanoFramework", "Controle e configuração do fotoperíodo", $sprite="img:icons/nanoFramework3.png")
    Container(timerCam, "Timelapse Timer Cam", "MicroPython, UiFlow", "Camera timelapse configuravel via web server", $sprite="img:icons/micropython-logo02.png")

    ContainerDb(db, "Datalogger microSD", "CSV", "Armazena as leituras obtidas dos sensores para visualização local", $sprite="file_csv")

    Boundary(vasos, "Vasos", "Sensor de Umidade do Solo") {
        Container(soilAtomA, "Solo A Atom Lite", "C#, .NET nanoFramework", "Leitura e calibragem do sensor de umidade do solo", $sprite="img:icons/nanoFramework3.png")
        Container(soilAtomB, "Solo B Atom Lite", "C#, .NET nanoFramework", "Leitura e calibragem do sensor de umidade do solo", $sprite="img:icons/nanoFramework3.png")
        ' Container(soilAtomC, "Solo C Atom Lite", "C#, .NET nanoFramework", "Leitura e calibragem do sensor de umidade do solo", $sprite="img:icons/nanoFramework3.png")
        ' Container(soilAtomD, "Solo D Atom Lite", "C#, .NET nanoFramework", "Leitura e calibragem do sensor de umidade do solo", $sprite="img:icons/nanoFramework3.png")
    }

    Rel_D(centralCore2, vasos, "Calibra as leituras do sensor")
    Rel_D(centralCore2, vasos, "Coleta dados de umidade do solo")
    Rel_U(centralCore2, dhtAtom, "Coleta as leituras de temperatura e umidade do ar")
    Rel_R(centralCore2, releAtom, "Obtém configuração de fotoperíodo atual")
    Rel_R(centralCore2, releAtom, "Obtém status atual do fotoperíodo")
    Rel_R(centralCore2, releAtom, "Configura o fotoperíodo")
    Rel_U(centralCore2, timerCam, "Obtém configuração do timelapse atual")
    Rel_U(centralCore2, timerCam, "Configura o timelapse")
    
    Rel_R(pessoa, centralCore2, "Monitora e Gerencia")
    Lay_U(centralCore2, pessoa)

    Rel_D(centralCore2, db, "Armazena dados")
    Rel_D(centralCore2, db, "Obtem dados para visualização")

    Lay_U(releAtom, dhtAtom)

    Lay_D(releAtom, db)
    Lay_D(db, vasos)

    ' Vasos horizontal
    Lay_L(soilAtomB, soilAtomA)
    ' Lay_R(soilAtomB, soilAtomC)

    ' Vasos vertical
    ' Lay_D(soilAtomA, soilAtomB)
    ' Lay_D(soilAtomB, soilAtomC)
    ' Lay_D(soilAtomC, soilAtomD)
}

SHOW_FLOATING_LEGEND()
Lay_Distance(LEGEND(), centralCore2, 1)
' LAYOUT_AS_SKETCH()

@enduml